export enum AmbienceDescription {
    'Academia' = 0,
    'Adega', // = 1
    'Banheiro simples',
    'Bar',
    'Biblioteca',
    'Closet',
    'Clínica',
    'Consultório',
    'Copa',
    'Corredores',
    'Cozinha americana',
    'Cozinha compacta',
    'Cozinha gourmet',
    'Cozinha planejada',
    'Diversos',
    'Escritório',
    'Fachadas de casas',
    'Fachadas de prédios',
    'Garagem',
    'Hall',
    'Home Office',
    'Jardim',
    'Jardim de inverno',
    'Lavabo',
    'Lavanderia',
    'Loja',
    'Piscina',
    'Playground',
    'Quarto de bebê',
    'Quarto de casal',
    'Quarto de menina',
    'Quarto de menino',
    'Quarto de solteiro',
    'Quintal',
    'Restaurante',
    'Sala de Estar',
    'Sala de Jantar',
    'Sala de banho',
    'Sala de jogos',
    'Salão de beleza',
    'Suíte',
    'Terraço',
    'Varanda',
    'Varanda gourmet',
}
